[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 256 # foundry 가 테스트 코드를 실행할 256개의 무작위 입력을 생성함

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
